message(STATUS "Removing build files...")
execute_process(COMMAND /usr/bin/cmake --build /home/teddycode/Desktop/Workspace/crypto-suites/bin/webassembly/cmd/wasm/pqcgo/pqmagic/build-linux --target clean)
file(GLOB_RECURSE SO_FILES "./*.so")
file(GLOB_RECURSE A_FILES "./*.a")
file(GLOB_RECURSE MRI_FILES "./*.mri")
message(STATUS "Removing shared library files...")
foreach(FILE ${SO_FILES})
   file(REMOVE ${FILE})
endforeach()
message(STATUS "Shared library files removed.")
message(STATUS "Removing static library files...")
foreach(FILE ${A_FILES})
   file(REMOVE ${FILE})
endforeach()
message(STATUS "Static library files removed.")
message(STATUS "Build files removed.")

if(EXISTS /home/teddycode/Desktop/Workspace/crypto-suites/bin/webassembly/cmd/wasm/pqcgo/libs/bin)
    message(STATUS "Removing files from /home/teddycode/Desktop/Workspace/crypto-suites/bin/webassembly/cmd/wasm/pqcgo/libs/bin...")
    file(GLOB BIN_FILES /home/teddycode/Desktop/Workspace/crypto-suites/bin/webassembly/cmd/wasm/pqcgo/libs/bin/*)
    foreach(FILE ${BIN_FILES})
        message(STATUS "	Remove ${FILE}.")
        file(REMOVE ${FILE})
    endforeach()
    message(STATUS "Files removed from /home/teddycode/Desktop/Workspace/crypto-suites/bin/webassembly/cmd/wasm/pqcgo/libs/bin.")
endif()
