nodes:
  - id: 0
    address: 127.0.0.1:8080
    rpc_address: 127.0.0.1:9080
    private_key_path: keys/r1.key
  - id: 1
    address: 127.0.0.1:8081
    rpc_address: 127.0.0.1:9081
    private_key_path: keys/r2.key
  # - id: 2
  #   address: 127.0.0.1:8082
  #   rpc_address: 127.0.0.1:9082
  #   private_key_path: keys/r3.key
  # - id: 3
  #   address: 127.0.0.1:8083
  #   rpc_address: 127.0.0.1:9083
  #   private_key_path: keys/r4.key
public_key_path: keys/pub.key

total: 2

log:
  level: info
  to_file: false
  filename: upgradeable_consensus.log

executor:
  type: local
  address: 127.0.0.1:9876

p2p:
  type: p2p-adaptor # p2p-adaptor currently only supports simple-whirly # sudo sysctl -w net.core.rmem_max=2500000
  # type: p2p

topic: this-is-consensus-topic-tttaaabbbcccddd-013

consensus:
  # type: "upgradeable"
  # consensus_id: 10001
  # upgradeable:
  #   commit_time: 5
  #   network_type: 0
  #   init_consensus:
  # type: hotstuff
  # hotstuff:
  #   consensus_id: 1000
  #   type: event-driven
  #   # type: basic
  #   batch_size: 10
  #   batch_timeout: 1
  #   timeout: 2
  #  type: whirly
  #  consensus_id: 1009
  #  whirly:
  #    type: simple
  #    # type: basic
  #    batch_size: 10
  #    timeout: 2
  #     # type: pow
  #     # consensus_id: 1008
  #     # pow:
  #     #   init_difficulty: 0x0010000000000000000000000000000000000000000000000000000000000000
  type: "pot"
  consensus_id: 10001
  pot:
    snum : 2
    sysPara: 2
    vdf0Iteration: 100000
    vdf1Iteration: 50000
    excutorAddress: 127.0.0.1:9877
    batchsize: 100
    timeout: 5
    commiteeSize : 4
    confirmDelay : 6
    slowrate : 6

# 100 - 5KB 10000 - 411K 30000-1290K