# ========= Basic Node Configuration =========
address_ip: "127.0.0.1"
address_start_port: "6060"
rpc_address_start_port: "7070"
data_dir: "data"
public_key_path: data/keys/pub.key
http_server_address: "0.0.0.0:8088"

# ======= Total Number of Replicas =======
total: 4

# ========= Log Configuration =========
log: 
  level: trace
  to_file: true
  filename: ./data/logs/pot_%s.log

# ========= Executor Configuration =========
executor:
  type: remote
  address: 127.0.0.1:9876

# ========= P2P Configuration =========
p2p:
  type: p2p-adaptor 
  # p2p-adaptor currently only supports simple-whirly 
  # sudo sysctl -w net.core.rmem_max=2500000
  # type: p2p

topic: this-is-consensus-topic-tttaaabbbcccddd-043

# ========= Consensus Configuration =========
consensus:
  # type: "upgradeable"
  # consensus_id: 10001
  # upgradeable:
  #   commit_time: 5
  #   network_type: 0
  #   init_consensus:
  # type: hotstuff
  # hotstuff:
  #   consensus_id: 1000
  #   type: event-driven
  #   # type: basic
  #   batch_size: 10
  #   batch_timeout: 1
  #   timeout: 2
  #  type: whirly
  #  consensus_id: 1009
  #  whirly:
  #    type: simple
  #    # type: basic
  #    batch_size: 10
  #    timeout: 2
  #     # type: pow
  #     # consensus_id: 1008
  #     # pow:
  #     #   init_difficulty: 0x0010000000000000000000000000000000000000000000000000000000000000
  type: "pot"
  consensus_id: 10001
  pot:
    snum : 2
    sysPara: 2
    vdf0Iteration: 100000
    vdf1Iteration: 80000
    batchsize: 100
    timeout: 5
    commiteeSize : 4
    confirmDelay : 6
    slowrate : 6
    vdfType : "wesolowski_rust"
    bciRpcAddress : 127.0.0.1:9866
    executorAddress: 127.0.0.1:9877

# 100 - 5KB 10000 - 411K 30000-1290K