# ========= Basic Node Configuration =========
address_ip: "0.0.0.0"
address_start_port: "6060"
rpc_address_start_port: "7070"
data_dir: "data"
public_key_path: data/keys/pub.key
http_server_address: "0.0.0.0:8088"

# ======= Total Number of Replicas =======
total: 1

# ========= Log Configuration =========
log: 
  level: debug
  to_file: false
  filename: ./data/logs/pot_%s.log

# ========= Executor Configuration =========
executor:
  type: remote
  address: executor:9877  # Use container name for docker-compose

# ========= P2P Configuration =========
p2p:
  type: p2p-adaptor 
  # p2p-adaptor currently only supports simple-whirly 
  # sudo sysctl -w net.core.rmem_max=2500000
  # type: p2p

topic: this-is-consensus-topic-tttaaabbbcccddd-043

# ========= Consensus Configuration =========
consensus:
  type: "pot"
  consensus_id: 10001
  pot:
    snum : 2
    sysPara: 2
    vdf0Iteration: 100000
    vdf1Iteration: 80000
    batchsize: 100
    timeout: 5
    commiteeSize : 4
    confirmDelay : 6
    slowrate : 6
    vdfType : "wesolowski_rust"
    bciRpcAddress : 127.0.0.1:9866
    executorAddress: executor:9877  # Use container name for docker-compose

# 100 - 5KB 10000 - 411K 30000-1290K
