// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pb/pot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_Block_Data     MessageType = 0
	MessageType_Block_Request  MessageType = 1
	MessageType_Block_Response MessageType = 2
	MessageType_PoT_Request    MessageType = 3
	MessageType_PoT_Response   MessageType = 4
	MessageType_PoT_Proof      MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Block_Data",
		1: "Block_Request",
		2: "Block_Response",
		3: "PoT_Request",
		4: "PoT_Response",
		5: "PoT_Proof",
	}
	MessageType_value = map[string]int32{
		"Block_Data":     0,
		"Block_Request":  1,
		"Block_Response": 2,
		"PoT_Request":    3,
		"PoT_Response":   4,
		"PoT_Proof":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_pot_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pb_pot_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{0}
}

type TxDataType int32

const (
	TxDataType_RawTx     TxDataType = 0
	TxDataType_ExcutedTx TxDataType = 1
)

// Enum value maps for TxDataType.
var (
	TxDataType_name = map[int32]string{
		0: "RawTx",
		1: "ExcutedTx",
	}
	TxDataType_value = map[string]int32{
		"RawTx":     0,
		"ExcutedTx": 1,
	}
)

func (x TxDataType) Enum() *TxDataType {
	p := new(TxDataType)
	*p = x
	return p
}

func (x TxDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_pot_proto_enumTypes[1].Descriptor()
}

func (TxDataType) Type() protoreflect.EnumType {
	return &file_pb_pot_proto_enumTypes[1]
}

func (x TxDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxDataType.Descriptor instead.
func (TxDataType) EnumDescriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{1}
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Txs    []*Tx   `protobuf:"bytes,2,rep,name=Txs,proto3" json:"Txs,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetTxs() []*Tx {
	if x != nil {
		return x.Txs
	}
	return nil
}

type Tx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Tx) Reset() {
	*x = Tx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tx) ProtoMessage() {}

func (x *Tx) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tx.ProtoReflect.Descriptor instead.
func (*Tx) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{1}
}

func (x *Tx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PoTMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType MessageType `protobuf:"varint,1,opt,name=MsgType,proto3,enum=pb.MessageType" json:"MsgType,omitempty"`
	MsgByte []byte      `protobuf:"bytes,2,opt,name=MsgByte,proto3" json:"MsgByte,omitempty"`
}

func (x *PoTMessage) Reset() {
	*x = PoTMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoTMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTMessage) ProtoMessage() {}

func (x *PoTMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTMessage.ProtoReflect.Descriptor instead.
func (*PoTMessage) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{2}
}

func (x *PoTMessage) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_Block_Data
}

func (x *PoTMessage) GetMsgByte() []byte {
	if x != nil {
		return x.MsgByte
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height     uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	ParentHash []byte   `protobuf:"bytes,2,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	UncleHash  [][]byte `protobuf:"bytes,3,rep,name=UncleHash,proto3" json:"UncleHash,omitempty"`
	Mixdigest  []byte   `protobuf:"bytes,4,opt,name=Mixdigest,proto3" json:"Mixdigest,omitempty"`
	Difficulty []byte   `protobuf:"bytes,5,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Nonce      int64    `protobuf:"varint,6,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Timestamp  []byte   `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	PoTProof   [][]byte `protobuf:"bytes,8,rep,name=PoTProof,proto3" json:"PoTProof,omitempty"`
	Address    int64    `protobuf:"varint,9,opt,name=Address,proto3" json:"Address,omitempty"`
	Hashes     []byte   `protobuf:"bytes,10,opt,name=Hashes,proto3" json:"Hashes,omitempty"`
	PeerId     string   `protobuf:"bytes,11,opt,name=PeerId,proto3" json:"PeerId,omitempty"`
	Pubkey     []byte   `protobuf:"bytes,12,opt,name=Pubkey,proto3" json:"Pubkey,omitempty"`
	Txhash     []byte   `protobuf:"bytes,13,opt,name=Txhash,proto3" json:"Txhash,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *Header) GetUncleHash() [][]byte {
	if x != nil {
		return x.UncleHash
	}
	return nil
}

func (x *Header) GetMixdigest() []byte {
	if x != nil {
		return x.Mixdigest
	}
	return nil
}

func (x *Header) GetDifficulty() []byte {
	if x != nil {
		return x.Difficulty
	}
	return nil
}

func (x *Header) GetNonce() int64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Header) GetTimestamp() []byte {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Header) GetPoTProof() [][]byte {
	if x != nil {
		return x.PoTProof
	}
	return nil
}

func (x *Header) GetAddress() int64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *Header) GetHashes() []byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *Header) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Header) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Header) GetTxhash() []byte {
	if x != nil {
		return x.Txhash
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      int32  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Operation []byte `protobuf:"bytes,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Proof     []byte `protobuf:"bytes,3,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Command) GetOperation() []byte {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Command) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type BlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Hashes []byte `protobuf:"bytes,2,opt,name=Hashes,proto3" json:"Hashes,omitempty"`
	Srcid  int64  `protobuf:"varint,3,opt,name=srcid,proto3" json:"srcid,omitempty"`
	Desid  int64  `protobuf:"varint,4,opt,name=desid,proto3" json:"desid,omitempty"`
	Src    string `protobuf:"bytes,5,opt,name=src,proto3" json:"src,omitempty"`
	Des    string `protobuf:"bytes,6,opt,name=des,proto3" json:"des,omitempty"`
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{5}
}

func (x *BlockRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockRequest) GetHashes() []byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *BlockRequest) GetSrcid() int64 {
	if x != nil {
		return x.Srcid
	}
	return 0
}

func (x *BlockRequest) GetDesid() int64 {
	if x != nil {
		return x.Desid
	}
	return 0
}

func (x *BlockRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *BlockRequest) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type BlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Src   string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Des   string `protobuf:"bytes,3,opt,name=des,proto3" json:"des,omitempty"`
	Srcid int64  `protobuf:"varint,4,opt,name=srcid,proto3" json:"srcid,omitempty"`
	Desid int64  `protobuf:"varint,5,opt,name=desid,proto3" json:"desid,omitempty"`
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{6}
}

func (x *BlockResponse) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockResponse) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *BlockResponse) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *BlockResponse) GetSrcid() int64 {
	if x != nil {
		return x.Srcid
	}
	return 0
}

func (x *BlockResponse) GetDesid() int64 {
	if x != nil {
		return x.Desid
	}
	return 0
}

type PoTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch uint64 `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Desid int64  `protobuf:"varint,2,opt,name=Desid,proto3" json:"Desid,omitempty"`
	Des   string `protobuf:"bytes,3,opt,name=Des,proto3" json:"Des,omitempty"`
	Srcid int64  `protobuf:"varint,4,opt,name=Srcid,proto3" json:"Srcid,omitempty"`
	Src   string `protobuf:"bytes,5,opt,name=Src,proto3" json:"Src,omitempty"`
}

func (x *PoTRequest) Reset() {
	*x = PoTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTRequest) ProtoMessage() {}

func (x *PoTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTRequest.ProtoReflect.Descriptor instead.
func (*PoTRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{7}
}

func (x *PoTRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PoTRequest) GetDesid() int64 {
	if x != nil {
		return x.Desid
	}
	return 0
}

func (x *PoTRequest) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *PoTRequest) GetSrcid() int64 {
	if x != nil {
		return x.Srcid
	}
	return 0
}

func (x *PoTRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

type PotProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch uint64 `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Proof []byte `protobuf:"bytes,2,opt,name=Proof,proto3" json:"Proof,omitempty"`
	Src   string `protobuf:"bytes,3,opt,name=Src,proto3" json:"Src,omitempty"`
	Des   string `protobuf:"bytes,4,opt,name=Des,proto3" json:"Des,omitempty"`
}

func (x *PotProof) Reset() {
	*x = PotProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PotProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PotProof) ProtoMessage() {}

func (x *PotProof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PotProof.ProtoReflect.Descriptor instead.
func (*PotProof) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{8}
}

func (x *PotProof) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PotProof) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *PotProof) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PotProof) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type PoTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Epoch uint64 `protobuf:"varint,1,opt,name=Epoch,proto3" json:"Epoch,omitempty"`
	Desid int64  `protobuf:"varint,2,opt,name=Desid,proto3" json:"Desid,omitempty"`
	Des   string `protobuf:"bytes,3,opt,name=Des,proto3" json:"Des,omitempty"`
	Srcid int64  `protobuf:"varint,4,opt,name=Srcid,proto3" json:"Srcid,omitempty"`
	Src   string `protobuf:"bytes,5,opt,name=Src,proto3" json:"Src,omitempty"`
	Proof []byte `protobuf:"bytes,6,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (x *PoTResponse) Reset() {
	*x = PoTResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoTResponse) ProtoMessage() {}

func (x *PoTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoTResponse.ProtoReflect.Descriptor instead.
func (*PoTResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{9}
}

func (x *PoTResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *PoTResponse) GetDesid() int64 {
	if x != nil {
		return x.Desid
	}
	return 0
}

func (x *PoTResponse) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *PoTResponse) GetSrcid() int64 {
	if x != nil {
		return x.Srcid
	}
	return 0
}

func (x *PoTResponse) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PoTResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type TxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxDataType TxDataType `protobuf:"varint,1,opt,name=TxDataType,proto3,enum=pb.TxDataType" json:"TxDataType,omitempty"`
	TxData     []byte     `protobuf:"bytes,2,opt,name=TxData,proto3" json:"TxData,omitempty"`
}

func (x *TxData) Reset() {
	*x = TxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxData) ProtoMessage() {}

func (x *TxData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxData.ProtoReflect.Descriptor instead.
func (*TxData) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{10}
}

func (x *TxData) GetTxDataType() TxDataType {
	if x != nil {
		return x.TxDataType
	}
	return TxDataType_RawTx
}

func (x *TxData) GetTxData() []byte {
	if x != nil {
		return x.TxData
	}
	return nil
}

type DciTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxID     []byte      `protobuf:"bytes,1,opt,name=TxID,proto3" json:"TxID,omitempty"`
	TxInput  []*TxInput  `protobuf:"bytes,2,rep,name=TxInput,proto3" json:"TxInput,omitempty"`
	TxOutput []*TxOutput `protobuf:"bytes,3,rep,name=TxOutput,proto3" json:"TxOutput,omitempty"`
	ChainID  int32       `protobuf:"varint,4,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *DciTx) Reset() {
	*x = DciTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DciTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DciTx) ProtoMessage() {}

func (x *DciTx) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DciTx.ProtoReflect.Descriptor instead.
func (*DciTx) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{11}
}

func (x *DciTx) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *DciTx) GetTxInput() []*TxInput {
	if x != nil {
		return x.TxInput
	}
	return nil
}

func (x *DciTx) GetTxOutput() []*TxOutput {
	if x != nil {
		return x.TxOutput
	}
	return nil
}

func (x *DciTx) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type TxInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsCoinbase bool   `protobuf:"varint,1,opt,name=IsCoinbase,proto3" json:"IsCoinbase,omitempty"`
	TxID       []byte `protobuf:"bytes,2,opt,name=TxID,proto3" json:"TxID,omitempty"`
	Voutput    int64  `protobuf:"varint,3,opt,name=Voutput,proto3" json:"Voutput,omitempty"`
	Scriptsig  []byte `protobuf:"bytes,4,opt,name=Scriptsig,proto3" json:"Scriptsig,omitempty"`
	Value      int64  `protobuf:"varint,5,opt,name=Value,proto3" json:"Value,omitempty"`
	Address    []byte `protobuf:"bytes,6,opt,name=Address,proto3" json:"Address,omitempty"`
	ChainID    int32  `protobuf:"varint,7,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *TxInput) Reset() {
	*x = TxInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxInput) ProtoMessage() {}

func (x *TxInput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxInput.ProtoReflect.Descriptor instead.
func (*TxInput) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{12}
}

func (x *TxInput) GetIsCoinbase() bool {
	if x != nil {
		return x.IsCoinbase
	}
	return false
}

func (x *TxInput) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *TxInput) GetVoutput() int64 {
	if x != nil {
		return x.Voutput
	}
	return 0
}

func (x *TxInput) GetScriptsig() []byte {
	if x != nil {
		return x.Scriptsig
	}
	return nil
}

func (x *TxInput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxInput) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxInput) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type TxOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Value    int64  `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	IsSpent  bool   `protobuf:"varint,3,opt,name=IsSpent,proto3" json:"IsSpent,omitempty"`
	ScriptPk []byte `protobuf:"bytes,4,opt,name=ScriptPk,proto3" json:"ScriptPk,omitempty"`
	ChainID  int32  `protobuf:"varint,5,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *TxOutput) Reset() {
	*x = TxOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxOutput) ProtoMessage() {}

func (x *TxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxOutput.ProtoReflect.Descriptor instead.
func (*TxOutput) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{13}
}

func (x *TxOutput) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TxOutput) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxOutput) GetIsSpent() bool {
	if x != nil {
		return x.IsSpent
	}
	return false
}

func (x *TxOutput) GetScriptPk() []byte {
	if x != nil {
		return x.ScriptPk
	}
	return nil
}

func (x *TxOutput) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type RawTxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxID     []byte      `protobuf:"bytes,1,opt,name=TxID,proto3" json:"TxID,omitempty"`
	TxInput  []*TxInput  `protobuf:"bytes,2,rep,name=TxInput,proto3" json:"TxInput,omitempty"`
	TxOutput []*TxOutput `protobuf:"bytes,3,rep,name=TxOutput,proto3" json:"TxOutput,omitempty"`
	ChainID  int32       `protobuf:"varint,4,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
}

func (x *RawTxData) Reset() {
	*x = RawTxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawTxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawTxData) ProtoMessage() {}

func (x *RawTxData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawTxData.ProtoReflect.Descriptor instead.
func (*RawTxData) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{14}
}

func (x *RawTxData) GetTxID() []byte {
	if x != nil {
		return x.TxID
	}
	return nil
}

func (x *RawTxData) GetTxInput() []*TxInput {
	if x != nil {
		return x.TxInput
	}
	return nil
}

func (x *RawTxData) GetTxOutput() []*TxOutput {
	if x != nil {
		return x.TxOutput
	}
	return nil
}

func (x *RawTxData) GetChainID() int32 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

type ExecutedTxData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutedHeight uint64 `protobuf:"varint,1,opt,name=ExecutedHeight,proto3" json:"ExecutedHeight,omitempty"`
	TxHash         []byte `protobuf:"bytes,2,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
}

func (x *ExecutedTxData) Reset() {
	*x = ExecutedTxData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutedTxData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedTxData) ProtoMessage() {}

func (x *ExecutedTxData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedTxData.ProtoReflect.Descriptor instead.
func (*ExecutedTxData) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{15}
}

func (x *ExecutedTxData) GetExecutedHeight() uint64 {
	if x != nil {
		return x.ExecutedHeight
	}
	return 0
}

func (x *ExecutedTxData) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type ExecuteBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ExecuteHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Txs    []*ExecutedTx  `protobuf:"bytes,2,rep,name=Txs,proto3" json:"Txs,omitempty"`
}

func (x *ExecuteBlock) Reset() {
	*x = ExecuteBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBlock) ProtoMessage() {}

func (x *ExecuteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBlock.ProtoReflect.Descriptor instead.
func (*ExecuteBlock) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteBlock) GetHeader() *ExecuteHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ExecuteBlock) GetTxs() []*ExecutedTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

type ExecuteHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    uint64 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	BlockHash []byte `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	ChainID   int64  `protobuf:"varint,3,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	TxsHash   []byte `protobuf:"bytes,4,opt,name=TxsHash,proto3" json:"TxsHash,omitempty"`
}

func (x *ExecuteHeader) Reset() {
	*x = ExecuteHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteHeader) ProtoMessage() {}

func (x *ExecuteHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteHeader.ProtoReflect.Descriptor instead.
func (*ExecuteHeader) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExecuteHeader) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecuteHeader) GetChainID() int64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *ExecuteHeader) GetTxsHash() []byte {
	if x != nil {
		return x.TxsHash
	}
	return nil
}

type ExecutedTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash []byte `protobuf:"bytes,1,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Height uint64 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ExecutedTx) Reset() {
	*x = ExecutedTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutedTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedTx) ProtoMessage() {}

func (x *ExecutedTx) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedTx.ProtoReflect.Descriptor instead.
func (*ExecutedTx) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{18}
}

func (x *ExecutedTx) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *ExecutedTx) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ExecutedTx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartHeight uint64 `protobuf:"varint,1,opt,name=StartHeight,proto3" json:"StartHeight,omitempty"`
	Des         string `protobuf:"bytes,2,opt,name=Des,proto3" json:"Des,omitempty"`
}

func (x *GetTxRequest) Reset() {
	*x = GetTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxRequest) ProtoMessage() {}

func (x *GetTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxRequest.ProtoReflect.Descriptor instead.
func (*GetTxRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{19}
}

func (x *GetTxRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *GetTxRequest) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

type GetTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start   uint64          `protobuf:"varint,1,opt,name=Start,proto3" json:"Start,omitempty"`
	End     uint64          `protobuf:"varint,2,opt,name=End,proto3" json:"End,omitempty"`
	Blocks  []*ExecuteBlock `protobuf:"bytes,3,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	Value   int64           `protobuf:"varint,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Address []byte          `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *GetTxResponse) Reset() {
	*x = GetTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTxResponse) ProtoMessage() {}

func (x *GetTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTxResponse.ProtoReflect.Descriptor instead.
func (*GetTxResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{20}
}

func (x *GetTxResponse) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetTxResponse) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GetTxResponse) GetBlocks() []*ExecuteBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetTxResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetTxResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type VerifyTxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs []*ExecutedTxData `protobuf:"bytes,1,rep,name=Txs,proto3" json:"Txs,omitempty"`
}

func (x *VerifyTxRequest) Reset() {
	*x = VerifyTxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxRequest) ProtoMessage() {}

func (x *VerifyTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxRequest.ProtoReflect.Descriptor instead.
func (*VerifyTxRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{21}
}

func (x *VerifyTxRequest) GetTxs() []*ExecutedTxData {
	if x != nil {
		return x.Txs
	}
	return nil
}

type VerifyTxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txs  []*ExecutedTxData `protobuf:"bytes,1,rep,name=Txs,proto3" json:"Txs,omitempty"`
	Flag []bool            `protobuf:"varint,2,rep,packed,name=flag,proto3" json:"flag,omitempty"`
}

func (x *VerifyTxResponse) Reset() {
	*x = VerifyTxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTxResponse) ProtoMessage() {}

func (x *VerifyTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTxResponse.ProtoReflect.Descriptor instead.
func (*VerifyTxResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{22}
}

func (x *VerifyTxResponse) GetTxs() []*ExecutedTxData {
	if x != nil {
		return x.Txs
	}
	return nil
}

func (x *VerifyTxResponse) GetFlag() []bool {
	if x != nil {
		return x.Flag
	}
	return nil
}

type DciReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  []byte    `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Amount   int64     `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	ChainID  int64     `protobuf:"varint,3,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	DciProof *DciProof `protobuf:"bytes,4,opt,name=DciProof,proto3" json:"DciProof,omitempty"`
}

func (x *DciReward) Reset() {
	*x = DciReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DciReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DciReward) ProtoMessage() {}

func (x *DciReward) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DciReward.ProtoReflect.Descriptor instead.
func (*DciReward) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{23}
}

func (x *DciReward) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *DciReward) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DciReward) GetChainID() int64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *DciReward) GetDciProof() *DciProof {
	if x != nil {
		return x.DciProof
	}
	return nil
}

type DciProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    uint64 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	BlockHash []byte `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	TxHash    []byte `protobuf:"bytes,3,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
}

func (x *DciProof) Reset() {
	*x = DciProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DciProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DciProof) ProtoMessage() {}

func (x *DciProof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DciProof.ProtoReflect.Descriptor instead.
func (*DciProof) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{24}
}

func (x *DciProof) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DciProof) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *DciProof) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

type SendDciRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DciReward []*DciReward `protobuf:"bytes,1,rep,name=DciReward,proto3" json:"DciReward,omitempty"`
}

func (x *SendDciRequest) Reset() {
	*x = SendDciRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDciRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDciRequest) ProtoMessage() {}

func (x *SendDciRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDciRequest.ProtoReflect.Descriptor instead.
func (*SendDciRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{25}
}

func (x *SendDciRequest) GetDciReward() []*DciReward {
	if x != nil {
		return x.DciReward
	}
	return nil
}

type SendDciResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"`
	Height    uint64 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
}

func (x *SendDciResponse) Reset() {
	*x = SendDciResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendDciResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDciResponse) ProtoMessage() {}

func (x *SendDciResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDciResponse.ProtoReflect.Descriptor instead.
func (*SendDciResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{26}
}

func (x *SendDciResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *SendDciResponse) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   []byte `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{27}
}

func (x *GetBalanceRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetBalanceRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   []byte      `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Balance   int64       `protobuf:"varint,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	TxOutputs []*TxOutput `protobuf:"bytes,3,rep,name=TxOutputs,proto3" json:"TxOutputs,omitempty"`
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{28}
}

func (x *GetBalanceResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *GetBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResponse) GetTxOutputs() []*TxOutput {
	if x != nil {
		return x.TxOutputs
	}
	return nil
}

type DevastateDciRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64      `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Tx     *RawTxData `protobuf:"bytes,2,opt,name=Tx,proto3" json:"Tx,omitempty"`
}

func (x *DevastateDciRequest) Reset() {
	*x = DevastateDciRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevastateDciRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateDciRequest) ProtoMessage() {}

func (x *DevastateDciRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateDciRequest.ProtoReflect.Descriptor instead.
func (*DevastateDciRequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{29}
}

func (x *DevastateDciRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DevastateDciRequest) GetTx() *RawTxData {
	if x != nil {
		return x.Tx
	}
	return nil
}

type DevastateDciResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *DevastateDciResponse) Reset() {
	*x = DevastateDciResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevastateDciResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevastateDciResponse) ProtoMessage() {}

func (x *DevastateDciResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevastateDciResponse.ProtoReflect.Descriptor instead.
func (*DevastateDciResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{30}
}

func (x *DevastateDciResponse) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type UTXOProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	TxHash []byte `protobuf:"bytes,2,opt,name=TxHash,proto3" json:"TxHash,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *UTXOProof) Reset() {
	*x = UTXOProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UTXOProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTXOProof) ProtoMessage() {}

func (x *UTXOProof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTXOProof.ProtoReflect.Descriptor instead.
func (*UTXOProof) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{31}
}

func (x *UTXOProof) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UTXOProof) GetTxHash() []byte {
	if x != nil {
		return x.TxHash
	}
	return nil
}

func (x *UTXOProof) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyUTXORequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  []byte `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To    []byte `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Value int64  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Proof []byte `protobuf:"bytes,4,opt,name=Proof,proto3" json:"Proof,omitempty"`
}

func (x *VerifyUTXORequest) Reset() {
	*x = VerifyUTXORequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUTXORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUTXORequest) ProtoMessage() {}

func (x *VerifyUTXORequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUTXORequest.ProtoReflect.Descriptor instead.
func (*VerifyUTXORequest) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{32}
}

func (x *VerifyUTXORequest) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *VerifyUTXORequest) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *VerifyUTXORequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *VerifyUTXORequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type VerifyUTXOResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *VerifyUTXOResponse) Reset() {
	*x = VerifyUTXOResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_pot_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUTXOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUTXOResponse) ProtoMessage() {}

func (x *VerifyUTXOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_pot_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUTXOResponse.ProtoReflect.Descriptor instead.
func (*VerifyUTXOResponse) Descriptor() ([]byte, []int) {
	return file_pb_pot_proto_rawDescGZIP(), []int{33}
}

func (x *VerifyUTXOResponse) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_pb_pot_proto protoreflect.FileDescriptor

var file_pb_pot_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x70, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x45, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62,
	0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x03, 0x54, 0x78, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x78, 0x52, 0x03, 0x54, 0x78, 0x73, 0x22, 0x18, 0x0a, 0x02, 0x54, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x0a, 0x50, 0x6f, 0x54, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x29, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x4d,
	0x73, 0x67, 0x42, 0x79, 0x74, 0x65, 0x22, 0xe6, 0x02, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x6e, 0x63,
	0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x55, 0x6e,
	0x63, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x69, 0x78, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x4d, 0x69, 0x78, 0x64,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x44, 0x69, 0x66, 0x66, 0x69,
	0x63, 0x75, 0x6c, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x54,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x6f, 0x54,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x51, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x22, 0x8e, 0x01, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x61, 0x73, 0x68, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x63, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x73,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x73, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x64, 0x65, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x72,
	0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x72, 0x63, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x64, 0x65, 0x73, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x0a, 0x50, 0x6f, 0x54, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65,
	0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x44, 0x65, 0x73, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x72, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x53, 0x72, 0x63, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x72, 0x63, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x72, 0x63, 0x22, 0x5a, 0x0a, 0x08, 0x50, 0x6f,
	0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x72, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x53, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x44, 0x65, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x50, 0x6f, 0x54, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x44, 0x65, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x44, 0x65, 0x73,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x44, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x72, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x72, 0x63, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x72,
	0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x72, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x72, 0x6f,
	0x6f, 0x66, 0x22, 0x50, 0x0a, 0x06, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x0a,
	0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0a, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x86, 0x01, 0x0a, 0x05, 0x44, 0x63, 0x69, 0x54, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x78, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78,
	0x49, 0x44, 0x12, 0x25, 0x0a, 0x07, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x52, 0x07, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x54, 0x78, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x08, 0x54, 0x78, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0xbf, 0x01,
	0x0a, 0x07, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x43,
	0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49,
	0x73, 0x43, 0x6f, 0x69, 0x6e, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x78, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x56, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x56, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x73, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x73, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22,
	0x8a, 0x01, 0x0a, 0x08, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x49, 0x73, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49,
	0x73, 0x53, 0x70, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x50, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x50, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x8a, 0x01, 0x0a,
	0x09, 0x52, 0x61, 0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x78,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x54, 0x78, 0x49, 0x44, 0x12, 0x25,
	0x0a, 0x07, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x07, 0x54, 0x78,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x08, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x08, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x0e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x64, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x0e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x5b, 0x0a, 0x0c, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x29, 0x0a, 0x06, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x03, 0x54, 0x78, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x64, 0x54, 0x78, 0x52, 0x03, 0x54, 0x78, 0x73, 0x22, 0x79, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x78, 0x73,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x54, 0x78, 0x73, 0x48,
	0x61, 0x73, 0x68, 0x22, 0x50, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x54,
	0x78, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44, 0x65, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x45, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x37, 0x0a,
	0x0f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x03, 0x54, 0x78, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64, 0x54, 0x78, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x03, 0x54, 0x78, 0x73, 0x22, 0x4c, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x54, 0x78,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x64, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x54, 0x78, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x08, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x44, 0x63, 0x69, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x28,
	0x0a, 0x08, 0x44, 0x63, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x63, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x08,
	0x44, 0x63, 0x69, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x58, 0x0a, 0x08, 0x44, 0x63, 0x69, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x22, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x44, 0x63, 0x69, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x63, 0x69,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x09, 0x44, 0x63, 0x69, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x22, 0x47, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x74, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x2a, 0x0a, 0x09, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x52, 0x09, 0x54, 0x78, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x4c, 0x0a,
	0x13, 0x44, 0x65, 0x76, 0x61, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x63, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x02,
	0x54, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x61,
	0x77, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x52, 0x02, 0x54, 0x78, 0x22, 0x2a, 0x0a, 0x14, 0x44,
	0x65, 0x76, 0x61, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x63, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x4f, 0x0a, 0x09, 0x55, 0x54, 0x58, 0x4f, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x54, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x63, 0x0a, 0x11, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x55, 0x54, 0x58, 0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x72, 0x6f,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x54,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x28, 0x0a,
	0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x54, 0x58, 0x4f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x2a, 0x76, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x44, 0x61, 0x74, 0x61, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x50, 0x6f, 0x54, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x50, 0x6f, 0x54, 0x5f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x50, 0x6f, 0x54, 0x5f, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x10, 0x05, 0x2a,
	0x26, 0x0a, 0x0a, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x52, 0x61, 0x77, 0x54, 0x78, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x78, 0x63, 0x75,
	0x74, 0x65, 0x64, 0x54, 0x78, 0x10, 0x01, 0x32, 0x78, 0x0a, 0x0b, 0x50, 0x6f, 0x54, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x78, 0x73,
	0x12, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x54, 0x78, 0x73, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x32, 0x85, 0x02, 0x0a, 0x0a, 0x44, 0x63, 0x69, 0x45, 0x78, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x34, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63, 0x69, 0x12, 0x12, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x63, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x61, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x44, 0x63, 0x69, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x61, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x63, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x61, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x63, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x55, 0x54, 0x58, 0x4f, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x55, 0x54, 0x58, 0x4f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x54, 0x58, 0x4f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_pot_proto_rawDescOnce sync.Once
	file_pb_pot_proto_rawDescData = file_pb_pot_proto_rawDesc
)

func file_pb_pot_proto_rawDescGZIP() []byte {
	file_pb_pot_proto_rawDescOnce.Do(func() {
		file_pb_pot_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_pot_proto_rawDescData)
	})
	return file_pb_pot_proto_rawDescData
}

var file_pb_pot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_pot_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_pb_pot_proto_goTypes = []interface{}{
	(MessageType)(0),             // 0: pb.MessageType
	(TxDataType)(0),              // 1: pb.TxDataType
	(*Block)(nil),                // 2: pb.Block
	(*Tx)(nil),                   // 3: pb.Tx
	(*PoTMessage)(nil),           // 4: pb.PoTMessage
	(*Header)(nil),               // 5: pb.Header
	(*Command)(nil),              // 6: pb.Command
	(*BlockRequest)(nil),         // 7: pb.BlockRequest
	(*BlockResponse)(nil),        // 8: pb.BlockResponse
	(*PoTRequest)(nil),           // 9: pb.PoTRequest
	(*PotProof)(nil),             // 10: pb.PotProof
	(*PoTResponse)(nil),          // 11: pb.PoTResponse
	(*TxData)(nil),               // 12: pb.TxData
	(*DciTx)(nil),                // 13: pb.DciTx
	(*TxInput)(nil),              // 14: pb.TxInput
	(*TxOutput)(nil),             // 15: pb.TxOutput
	(*RawTxData)(nil),            // 16: pb.RawTxData
	(*ExecutedTxData)(nil),       // 17: pb.ExecutedTxData
	(*ExecuteBlock)(nil),         // 18: pb.ExecuteBlock
	(*ExecuteHeader)(nil),        // 19: pb.ExecuteHeader
	(*ExecutedTx)(nil),           // 20: pb.ExecutedTx
	(*GetTxRequest)(nil),         // 21: pb.GetTxRequest
	(*GetTxResponse)(nil),        // 22: pb.GetTxResponse
	(*VerifyTxRequest)(nil),      // 23: pb.VerifyTxRequest
	(*VerifyTxResponse)(nil),     // 24: pb.VerifyTxResponse
	(*DciReward)(nil),            // 25: pb.DciReward
	(*DciProof)(nil),             // 26: pb.DciProof
	(*SendDciRequest)(nil),       // 27: pb.SendDciRequest
	(*SendDciResponse)(nil),      // 28: pb.SendDciResponse
	(*GetBalanceRequest)(nil),    // 29: pb.GetBalanceRequest
	(*GetBalanceResponse)(nil),   // 30: pb.GetBalanceResponse
	(*DevastateDciRequest)(nil),  // 31: pb.DevastateDciRequest
	(*DevastateDciResponse)(nil), // 32: pb.DevastateDciResponse
	(*UTXOProof)(nil),            // 33: pb.UTXOProof
	(*VerifyUTXORequest)(nil),    // 34: pb.VerifyUTXORequest
	(*VerifyUTXOResponse)(nil),   // 35: pb.VerifyUTXOResponse
}
var file_pb_pot_proto_depIdxs = []int32{
	5,  // 0: pb.Block.Header:type_name -> pb.Header
	3,  // 1: pb.Block.Txs:type_name -> pb.Tx
	0,  // 2: pb.PoTMessage.MsgType:type_name -> pb.MessageType
	2,  // 3: pb.BlockResponse.block:type_name -> pb.Block
	1,  // 4: pb.TxData.TxDataType:type_name -> pb.TxDataType
	14, // 5: pb.DciTx.TxInput:type_name -> pb.TxInput
	15, // 6: pb.DciTx.TxOutput:type_name -> pb.TxOutput
	14, // 7: pb.RawTxData.TxInput:type_name -> pb.TxInput
	15, // 8: pb.RawTxData.TxOutput:type_name -> pb.TxOutput
	19, // 9: pb.ExecuteBlock.Header:type_name -> pb.ExecuteHeader
	20, // 10: pb.ExecuteBlock.Txs:type_name -> pb.ExecutedTx
	18, // 11: pb.GetTxResponse.Blocks:type_name -> pb.ExecuteBlock
	17, // 12: pb.VerifyTxRequest.Txs:type_name -> pb.ExecutedTxData
	17, // 13: pb.VerifyTxResponse.Txs:type_name -> pb.ExecutedTxData
	26, // 14: pb.DciReward.DciProof:type_name -> pb.DciProof
	25, // 15: pb.SendDciRequest.DciReward:type_name -> pb.DciReward
	15, // 16: pb.GetBalanceResponse.TxOutputs:type_name -> pb.TxOutput
	16, // 17: pb.DevastateDciRequest.Tx:type_name -> pb.RawTxData
	21, // 18: pb.PoTExecutor.GetTxs:input_type -> pb.GetTxRequest
	23, // 19: pb.PoTExecutor.VerifyTxs:input_type -> pb.VerifyTxRequest
	27, // 20: pb.DciExector.SendDci:input_type -> pb.SendDciRequest
	29, // 21: pb.DciExector.GetBalance:input_type -> pb.GetBalanceRequest
	31, // 22: pb.DciExector.DevastateDci:input_type -> pb.DevastateDciRequest
	34, // 23: pb.DciExector.VerifyUTXO:input_type -> pb.VerifyUTXORequest
	22, // 24: pb.PoTExecutor.GetTxs:output_type -> pb.GetTxResponse
	24, // 25: pb.PoTExecutor.VerifyTxs:output_type -> pb.VerifyTxResponse
	28, // 26: pb.DciExector.SendDci:output_type -> pb.SendDciResponse
	30, // 27: pb.DciExector.GetBalance:output_type -> pb.GetBalanceResponse
	32, // 28: pb.DciExector.DevastateDci:output_type -> pb.DevastateDciResponse
	35, // 29: pb.DciExector.VerifyUTXO:output_type -> pb.VerifyUTXOResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_pb_pot_proto_init() }
func file_pb_pot_proto_init() {
	if File_pb_pot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_pot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoTMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PotProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoTResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DciTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawTxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutedTxData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutedTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyTxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DciReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DciProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDciRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendDciResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevastateDciRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevastateDciResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UTXOProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyUTXORequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_pot_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyUTXOResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_pot_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_pot_proto_goTypes,
		DependencyIndexes: file_pb_pot_proto_depIdxs,
		EnumInfos:         file_pb_pot_proto_enumTypes,
		MessageInfos:      file_pb_pot_proto_msgTypes,
	}.Build()
	File_pb_pot_proto = out.File
	file_pb_pot_proto_rawDesc = nil
	file_pb_pot_proto_goTypes = nil
	file_pb_pot_proto_depIdxs = nil
}
