// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.0
// source: pb/pot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoTExecutor_GetTxs_FullMethodName             = "/pb.PoTExecutor/GetTxs"
	PoTExecutor_VerifyTxs_FullMethodName          = "/pb.PoTExecutor/VerifyTxs"
	PoTExecutor_ExecuteTxs_FullMethodName         = "/pb.PoTExecutor/ExecuteTxs"
	PoTExecutor_VerifyIncensentive_FullMethodName = "/pb.PoTExecutor/VerifyIncensentive"
)

// PoTExecutorClient is the client API for PoTExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoTExecutorClient interface {
	GetTxs(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*GetTxResponse, error)
	VerifyTxs(ctx context.Context, in *VerifyTxRequest, opts ...grpc.CallOption) (*VerifyTxResponse, error)
	ExecuteTxs(ctx context.Context, in *ExecuteTxRequest, opts ...grpc.CallOption) (*ExecuteTxResponse, error)
	VerifyIncensentive(ctx context.Context, in *IncensentiveVerifyRequest, opts ...grpc.CallOption) (*IncensentiveVerifyResponse, error)
}

type poTExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewPoTExecutorClient(cc grpc.ClientConnInterface) PoTExecutorClient {
	return &poTExecutorClient{cc}
}

func (c *poTExecutorClient) GetTxs(ctx context.Context, in *GetTxRequest, opts ...grpc.CallOption) (*GetTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTxResponse)
	err := c.cc.Invoke(ctx, PoTExecutor_GetTxs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTExecutorClient) VerifyTxs(ctx context.Context, in *VerifyTxRequest, opts ...grpc.CallOption) (*VerifyTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTxResponse)
	err := c.cc.Invoke(ctx, PoTExecutor_VerifyTxs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTExecutorClient) ExecuteTxs(ctx context.Context, in *ExecuteTxRequest, opts ...grpc.CallOption) (*ExecuteTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTxResponse)
	err := c.cc.Invoke(ctx, PoTExecutor_ExecuteTxs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTExecutorClient) VerifyIncensentive(ctx context.Context, in *IncensentiveVerifyRequest, opts ...grpc.CallOption) (*IncensentiveVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncensentiveVerifyResponse)
	err := c.cc.Invoke(ctx, PoTExecutor_VerifyIncensentive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoTExecutorServer is the server API for PoTExecutor service.
// All implementations should embed UnimplementedPoTExecutorServer
// for forward compatibility.
type PoTExecutorServer interface {
	GetTxs(context.Context, *GetTxRequest) (*GetTxResponse, error)
	VerifyTxs(context.Context, *VerifyTxRequest) (*VerifyTxResponse, error)
	ExecuteTxs(context.Context, *ExecuteTxRequest) (*ExecuteTxResponse, error)
	VerifyIncensentive(context.Context, *IncensentiveVerifyRequest) (*IncensentiveVerifyResponse, error)
}

// UnimplementedPoTExecutorServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoTExecutorServer struct{}

func (UnimplementedPoTExecutorServer) GetTxs(context.Context, *GetTxRequest) (*GetTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxs not implemented")
}
func (UnimplementedPoTExecutorServer) VerifyTxs(context.Context, *VerifyTxRequest) (*VerifyTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTxs not implemented")
}
func (UnimplementedPoTExecutorServer) ExecuteTxs(context.Context, *ExecuteTxRequest) (*ExecuteTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTxs not implemented")
}
func (UnimplementedPoTExecutorServer) VerifyIncensentive(context.Context, *IncensentiveVerifyRequest) (*IncensentiveVerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyIncensentive not implemented")
}
func (UnimplementedPoTExecutorServer) testEmbeddedByValue() {}

// UnsafePoTExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoTExecutorServer will
// result in compilation errors.
type UnsafePoTExecutorServer interface {
	mustEmbedUnimplementedPoTExecutorServer()
}

func RegisterPoTExecutorServer(s grpc.ServiceRegistrar, srv PoTExecutorServer) {
	// If the following call pancis, it indicates UnimplementedPoTExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoTExecutor_ServiceDesc, srv)
}

func _PoTExecutor_GetTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTExecutorServer).GetTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTExecutor_GetTxs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTExecutorServer).GetTxs(ctx, req.(*GetTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTExecutor_VerifyTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTExecutorServer).VerifyTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTExecutor_VerifyTxs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTExecutorServer).VerifyTxs(ctx, req.(*VerifyTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTExecutor_ExecuteTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTExecutorServer).ExecuteTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTExecutor_ExecuteTxs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTExecutorServer).ExecuteTxs(ctx, req.(*ExecuteTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTExecutor_VerifyIncensentive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncensentiveVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTExecutorServer).VerifyIncensentive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTExecutor_VerifyIncensentive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTExecutorServer).VerifyIncensentive(ctx, req.(*IncensentiveVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoTExecutor_ServiceDesc is the grpc.ServiceDesc for PoTExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoTExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PoTExecutor",
	HandlerType: (*PoTExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTxs",
			Handler:    _PoTExecutor_GetTxs_Handler,
		},
		{
			MethodName: "VerifyTxs",
			Handler:    _PoTExecutor_VerifyTxs_Handler,
		},
		{
			MethodName: "ExecuteTxs",
			Handler:    _PoTExecutor_ExecuteTxs_Handler,
		},
		{
			MethodName: "VerifyIncensentive",
			Handler:    _PoTExecutor_VerifyIncensentive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/pot.proto",
}

const (
	PoTConsensus_SendBci_FullMethodName                          = "/pb.PoTConsensus/SendBci"
	PoTConsensus_GetBalance_FullMethodName                       = "/pb.PoTConsensus/GetBalance"
	PoTConsensus_VerifyUTXO_FullMethodName                       = "/pb.PoTConsensus/VerifyUTXO"
	PoTConsensus_CreateLockTransaction_FullMethodName            = "/pb.PoTConsensus/CreateLockTransaction"
	PoTConsensus_CreateLockTransferTransaction_FullMethodName    = "/pb.PoTConsensus/CreateLockTransferTransaction"
	PoTConsensus_CreateDevastateTransaction_FullMethodName       = "/pb.PoTConsensus/CreateDevastateTransaction"
	PoTConsensus_CreateNonLockTransferTransaction_FullMethodName = "/pb.PoTConsensus/CreateNonLockTransferTransaction"
	PoTConsensus_CreateBciToVsiTransaction_FullMethodName        = "/pb.PoTConsensus/CreateBciToVsiTransaction"
)

// PoTConsensusClient is the client API for PoTConsensus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoTConsensusClient interface {
	SendBci(ctx context.Context, in *SendBciRequest, opts ...grpc.CallOption) (*SendBciResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	VerifyUTXO(ctx context.Context, in *VerifyUTXORequest, opts ...grpc.CallOption) (*VerifyUTXOResponse, error)
	CreateLockTransaction(ctx context.Context, in *CreateLockTransactionRequest, opts ...grpc.CallOption) (*CreateLockTransactionResponse, error)
	CreateLockTransferTransaction(ctx context.Context, in *CreateLockTransferTransactionRequest, opts ...grpc.CallOption) (*CreateLockTransferTransactionResponse, error)
	CreateDevastateTransaction(ctx context.Context, in *CreateDevastateTransactionRequest, opts ...grpc.CallOption) (*CreateDevastateTransactionResponse, error)
	CreateNonLockTransferTransaction(ctx context.Context, in *CreateNonLockTransferTransactionRequest, opts ...grpc.CallOption) (*CreateNonLockTransferTransactionResponse, error)
	CreateBciToVsiTransaction(ctx context.Context, in *CreateBciToVsiRequest, opts ...grpc.CallOption) (*CreateBciToVsiResponse, error)
}

type poTConsensusClient struct {
	cc grpc.ClientConnInterface
}

func NewPoTConsensusClient(cc grpc.ClientConnInterface) PoTConsensusClient {
	return &poTConsensusClient{cc}
}

func (c *poTConsensusClient) SendBci(ctx context.Context, in *SendBciRequest, opts ...grpc.CallOption) (*SendBciResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendBciResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_SendBci_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) VerifyUTXO(ctx context.Context, in *VerifyUTXORequest, opts ...grpc.CallOption) (*VerifyUTXOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUTXOResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_VerifyUTXO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) CreateLockTransaction(ctx context.Context, in *CreateLockTransactionRequest, opts ...grpc.CallOption) (*CreateLockTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLockTransactionResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_CreateLockTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) CreateLockTransferTransaction(ctx context.Context, in *CreateLockTransferTransactionRequest, opts ...grpc.CallOption) (*CreateLockTransferTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLockTransferTransactionResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_CreateLockTransferTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) CreateDevastateTransaction(ctx context.Context, in *CreateDevastateTransactionRequest, opts ...grpc.CallOption) (*CreateDevastateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDevastateTransactionResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_CreateDevastateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) CreateNonLockTransferTransaction(ctx context.Context, in *CreateNonLockTransferTransactionRequest, opts ...grpc.CallOption) (*CreateNonLockTransferTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNonLockTransferTransactionResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_CreateNonLockTransferTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poTConsensusClient) CreateBciToVsiTransaction(ctx context.Context, in *CreateBciToVsiRequest, opts ...grpc.CallOption) (*CreateBciToVsiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBciToVsiResponse)
	err := c.cc.Invoke(ctx, PoTConsensus_CreateBciToVsiTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoTConsensusServer is the server API for PoTConsensus service.
// All implementations should embed UnimplementedPoTConsensusServer
// for forward compatibility.
type PoTConsensusServer interface {
	SendBci(context.Context, *SendBciRequest) (*SendBciResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	VerifyUTXO(context.Context, *VerifyUTXORequest) (*VerifyUTXOResponse, error)
	CreateLockTransaction(context.Context, *CreateLockTransactionRequest) (*CreateLockTransactionResponse, error)
	CreateLockTransferTransaction(context.Context, *CreateLockTransferTransactionRequest) (*CreateLockTransferTransactionResponse, error)
	CreateDevastateTransaction(context.Context, *CreateDevastateTransactionRequest) (*CreateDevastateTransactionResponse, error)
	CreateNonLockTransferTransaction(context.Context, *CreateNonLockTransferTransactionRequest) (*CreateNonLockTransferTransactionResponse, error)
	CreateBciToVsiTransaction(context.Context, *CreateBciToVsiRequest) (*CreateBciToVsiResponse, error)
}

// UnimplementedPoTConsensusServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoTConsensusServer struct{}

func (UnimplementedPoTConsensusServer) SendBci(context.Context, *SendBciRequest) (*SendBciResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBci not implemented")
}
func (UnimplementedPoTConsensusServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedPoTConsensusServer) VerifyUTXO(context.Context, *VerifyUTXORequest) (*VerifyUTXOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUTXO not implemented")
}
func (UnimplementedPoTConsensusServer) CreateLockTransaction(context.Context, *CreateLockTransactionRequest) (*CreateLockTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLockTransaction not implemented")
}
func (UnimplementedPoTConsensusServer) CreateLockTransferTransaction(context.Context, *CreateLockTransferTransactionRequest) (*CreateLockTransferTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLockTransferTransaction not implemented")
}
func (UnimplementedPoTConsensusServer) CreateDevastateTransaction(context.Context, *CreateDevastateTransactionRequest) (*CreateDevastateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevastateTransaction not implemented")
}
func (UnimplementedPoTConsensusServer) CreateNonLockTransferTransaction(context.Context, *CreateNonLockTransferTransactionRequest) (*CreateNonLockTransferTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNonLockTransferTransaction not implemented")
}
func (UnimplementedPoTConsensusServer) CreateBciToVsiTransaction(context.Context, *CreateBciToVsiRequest) (*CreateBciToVsiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBciToVsiTransaction not implemented")
}
func (UnimplementedPoTConsensusServer) testEmbeddedByValue() {}

// UnsafePoTConsensusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoTConsensusServer will
// result in compilation errors.
type UnsafePoTConsensusServer interface {
	mustEmbedUnimplementedPoTConsensusServer()
}

func RegisterPoTConsensusServer(s grpc.ServiceRegistrar, srv PoTConsensusServer) {
	// If the following call pancis, it indicates UnimplementedPoTConsensusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoTConsensus_ServiceDesc, srv)
}

func _PoTConsensus_SendBci_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBciRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).SendBci(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_SendBci_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).SendBci(ctx, req.(*SendBciRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_VerifyUTXO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUTXORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).VerifyUTXO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_VerifyUTXO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).VerifyUTXO(ctx, req.(*VerifyUTXORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_CreateLockTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLockTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).CreateLockTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_CreateLockTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).CreateLockTransaction(ctx, req.(*CreateLockTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_CreateLockTransferTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLockTransferTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).CreateLockTransferTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_CreateLockTransferTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).CreateLockTransferTransaction(ctx, req.(*CreateLockTransferTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_CreateDevastateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDevastateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).CreateDevastateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_CreateDevastateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).CreateDevastateTransaction(ctx, req.(*CreateDevastateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_CreateNonLockTransferTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNonLockTransferTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).CreateNonLockTransferTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_CreateNonLockTransferTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).CreateNonLockTransferTransaction(ctx, req.(*CreateNonLockTransferTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoTConsensus_CreateBciToVsiTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBciToVsiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoTConsensusServer).CreateBciToVsiTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoTConsensus_CreateBciToVsiTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoTConsensusServer).CreateBciToVsiTransaction(ctx, req.(*CreateBciToVsiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoTConsensus_ServiceDesc is the grpc.ServiceDesc for PoTConsensus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoTConsensus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PoTConsensus",
	HandlerType: (*PoTConsensusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendBci",
			Handler:    _PoTConsensus_SendBci_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _PoTConsensus_GetBalance_Handler,
		},
		{
			MethodName: "VerifyUTXO",
			Handler:    _PoTConsensus_VerifyUTXO_Handler,
		},
		{
			MethodName: "CreateLockTransaction",
			Handler:    _PoTConsensus_CreateLockTransaction_Handler,
		},
		{
			MethodName: "CreateLockTransferTransaction",
			Handler:    _PoTConsensus_CreateLockTransferTransaction_Handler,
		},
		{
			MethodName: "CreateDevastateTransaction",
			Handler:    _PoTConsensus_CreateDevastateTransaction_Handler,
		},
		{
			MethodName: "CreateNonLockTransferTransaction",
			Handler:    _PoTConsensus_CreateNonLockTransferTransaction_Handler,
		},
		{
			MethodName: "CreateBciToVsiTransaction",
			Handler:    _PoTConsensus_CreateBciToVsiTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/pot.proto",
}
