// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a temporary manual implementation until protoc is available

package pb

// UpgradePhase 升级阶段枚举
type UpgradePhase int32

const (
	UpgradePhase_PHASE_NONE         UpgradePhase = 0
	UpgradePhase_PHASE_PROPOSED     UpgradePhase = 1
	UpgradePhase_PHASE_PREEXEC      UpgradePhase = 2
	UpgradePhase_PHASE_SWITCH_READY UpgradePhase = 3
	UpgradePhase_PHASE_SWITCHED     UpgradePhase = 4
	UpgradePhase_PHASE_FINALIZED    UpgradePhase = 5
	UpgradePhase_PHASE_ROLLBACK     UpgradePhase = 6
)

// ExecutionStatus 执行状态枚举
type ExecutionStatus int32

const (
	ExecutionStatus_STATUS_RUNNING ExecutionStatus = 0
	ExecutionStatus_STATUS_SUCCESS ExecutionStatus = 1
	ExecutionStatus_STATUS_FAILED  ExecutionStatus = 2
)

// RollbackCondition 回退条件
type RollbackCondition struct {
	MaxErrorRate       float64 `protobuf:"fixed64,1,opt,name=max_error_rate,json=maxErrorRate,proto3" json:"max_error_rate,omitempty"`
	MaxLatencyIncrease float64 `protobuf:"fixed64,2,opt,name=max_latency_increase,json=maxLatencyIncrease,proto3" json:"max_latency_increase,omitempty"`
	MinThroughputRatio float64 `protobuf:"fixed64,3,opt,name=min_throughput_ratio,json=minThroughputRatio,proto3" json:"min_throughput_ratio,omitempty"`
	TimeoutBlocks      uint64  `protobuf:"varint,4,opt,name=timeout_blocks,json=timeoutBlocks,proto3" json:"timeout_blocks,omitempty"`
}

// UpgradeConfigTransaction 升级配置交易
type UpgradeConfigTransaction struct {
	ProposalId          []byte             `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	TargetConsensus     string             `protobuf:"bytes,2,opt,name=target_consensus,json=targetConsensus,proto3" json:"target_consensus,omitempty"`
	CdlYaml             string             `protobuf:"bytes,3,opt,name=cdl_yaml,json=cdlYaml,proto3" json:"cdl_yaml,omitempty"`
	ForkHeight          uint64             `protobuf:"varint,4,opt,name=fork_height,json=forkHeight,proto3" json:"fork_height,omitempty"`
	PreexecStartHeight  uint64             `protobuf:"varint,5,opt,name=preexec_start_height,json=preexecStartHeight,proto3" json:"preexec_start_height,omitempty"`
	SwitchHeight        uint64             `protobuf:"varint,6,opt,name=switch_height,json=switchHeight,proto3" json:"switch_height,omitempty"`
	RollbackCondition   *RollbackCondition `protobuf:"bytes,7,opt,name=rollback_condition,json=rollbackCondition,proto3" json:"rollback_condition,omitempty"`
	CommitteeSignatures [][]byte           `protobuf:"bytes,8,rep,name=committee_signatures,json=committeeSignatures,proto3" json:"committee_signatures,omitempty"`
	CommitteePubkeys    [][]byte           `protobuf:"bytes,9,rep,name=committee_pubkeys,json=committeePubkeys,proto3" json:"committee_pubkeys,omitempty"`
	Threshold           uint32             `protobuf:"varint,10,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Incentive           uint64             `protobuf:"varint,11,opt,name=incentive,proto3" json:"incentive,omitempty"`
	Timestamp           int64              `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Proposer            []byte             `protobuf:"bytes,13,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Description         string             `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	ConsensusParams     string             `protobuf:"bytes,15,opt,name=consensus_params,json=consensusParams,proto3" json:"consensus_params,omitempty"`
	ConsensusId         int64              `protobuf:"varint,16,opt,name=consensus_id,json=consensusId,proto3" json:"consensus_id,omitempty"`
	MetadataHash        []byte             `protobuf:"bytes,17,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
	Nonce               uint64             `protobuf:"varint,18,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

// UpgradeConfirmTransaction 升级确认交易
type UpgradeConfirmTransaction struct {
	ProposalId      []byte `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	ConfirmerId     int64  `protobuf:"varint,2,opt,name=confirmer_id,json=confirmerId,proto3" json:"confirmer_id,omitempty"`
	Signature       []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey       []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Timestamp       int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConfirmedHeight uint64 `protobuf:"varint,6,opt,name=confirmed_height,json=confirmedHeight,proto3" json:"confirmed_height,omitempty"`
	Comment         string `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Approved        bool   `protobuf:"varint,8,opt,name=approved,proto3" json:"approved,omitempty"`
}

// BlockMetric 单个区块指标
type BlockMetric struct {
	Height    uint64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockTime float64 `protobuf:"fixed64,2,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	TxCount   uint32  `protobuf:"varint,3,opt,name=tx_count,json=txCount,proto3" json:"tx_count,omitempty"`
	Success   bool    `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg  string  `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
}

// ExecutionMetrics 执行指标
type ExecutionMetrics struct {
	AvgBlockTime  float64        `protobuf:"fixed64,1,opt,name=avg_block_time,json=avgBlockTime,proto3" json:"avg_block_time,omitempty"`
	AvgThroughput float64        `protobuf:"fixed64,2,opt,name=avg_throughput,json=avgThroughput,proto3" json:"avg_throughput,omitempty"`
	ErrorRate     float64        `protobuf:"fixed64,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	TotalBlocks   uint64         `protobuf:"varint,4,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"`
	FailedBlocks  uint64         `protobuf:"varint,5,opt,name=failed_blocks,json=failedBlocks,proto3" json:"failed_blocks,omitempty"`
	Timestamp     int64          `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlockMetrics  []*BlockMetric `protobuf:"bytes,7,rep,name=block_metrics,json=blockMetrics,proto3" json:"block_metrics,omitempty"`
}

// PreexecHeader 预执行链区块头
type PreexecHeader struct {
	Height      uint64          `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	ParentHash  []byte          `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	TxHash      []byte          `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	StateRoot   []byte          `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Timestamp   int64           `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConsensusId int64           `protobuf:"varint,6,opt,name=consensus_id,json=consensusId,proto3" json:"consensus_id,omitempty"`
	Proposer    []byte          `protobuf:"bytes,7,opt,name=proposer,proto3" json:"proposer,omitempty"`
	ForkPoint   uint64          `protobuf:"varint,8,opt,name=fork_point,json=forkPoint,proto3" json:"fork_point,omitempty"`
	Status      ExecutionStatus `protobuf:"varint,9,opt,name=status,proto3,enum=pb.ExecutionStatus" json:"status,omitempty"`
}

// ConsensusDescriptorCDL CDL 共识描述
type ConsensusDescriptorCDL struct {
	Name                    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version                 string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Type                    string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Components              []byte `protobuf:"bytes,4,opt,name=components,proto3" json:"components,omitempty"`
	Parameters              []byte `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Phases                  []byte `protobuf:"bytes,6,opt,name=phases,proto3" json:"phases,omitempty"`
	StateMachine            []byte `protobuf:"bytes,7,opt,name=state_machine,json=stateMachine,proto3" json:"state_machine,omitempty"`
	SafetyProperties        []byte `protobuf:"bytes,8,opt,name=safety_properties,json=safetyProperties,proto3" json:"safety_properties,omitempty"`
	PerformanceRequirements []byte `protobuf:"bytes,9,opt,name=performance_requirements,json=performanceRequirements,proto3" json:"performance_requirements,omitempty"`
}

// Reset methods for protobuf compatibility
func (m *RollbackCondition) Reset()         { *m = RollbackCondition{} }
func (m *UpgradeConfigTransaction) Reset()  { *m = UpgradeConfigTransaction{} }
func (m *UpgradeConfirmTransaction) Reset() { *m = UpgradeConfirmTransaction{} }
func (m *BlockMetric) Reset()               { *m = BlockMetric{} }
func (m *ExecutionMetrics) Reset()          { *m = ExecutionMetrics{} }
func (m *PreexecHeader) Reset()             { *m = PreexecHeader{} }
func (m *ConsensusDescriptorCDL) Reset()    { *m = ConsensusDescriptorCDL{} }

// String methods
func (m *RollbackCondition) String() string         { return "RollbackCondition{...}" }
func (m *UpgradeConfigTransaction) String() string  { return "UpgradeConfigTransaction{...}" }
func (m *UpgradeConfirmTransaction) String() string { return "UpgradeConfirmTransaction{...}" }
func (m *BlockMetric) String() string               { return "BlockMetric{...}" }
func (m *ExecutionMetrics) String() string          { return "ExecutionMetrics{...}" }
func (m *PreexecHeader) String() string             { return "PreexecHeader{...}" }
func (m *ConsensusDescriptorCDL) String() string    { return "ConsensusDescriptorCDL{...}" }

// ProtoMessage methods
func (*RollbackCondition) ProtoMessage()         {}
func (*UpgradeConfigTransaction) ProtoMessage()  {}
func (*UpgradeConfirmTransaction) ProtoMessage() {}
func (*BlockMetric) ProtoMessage()               {}
func (*ExecutionMetrics) ProtoMessage()          {}
func (*PreexecHeader) ProtoMessage()             {}
func (*ConsensusDescriptorCDL) ProtoMessage()    {}
