// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: pb/bls12_381.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bls12-381 Fr in big endian
type Fr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E1 uint64 `protobuf:"varint,1,opt,name=e1,proto3" json:"e1,omitempty"`
	E2 uint64 `protobuf:"varint,2,opt,name=e2,proto3" json:"e2,omitempty"`
	E3 uint64 `protobuf:"varint,3,opt,name=e3,proto3" json:"e3,omitempty"`
	E4 uint64 `protobuf:"varint,4,opt,name=e4,proto3" json:"e4,omitempty"`
}

func (x *Fr) Reset() {
	*x = Fr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_bls12_381_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fr) ProtoMessage() {}

func (x *Fr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bls12_381_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fr.ProtoReflect.Descriptor instead.
func (*Fr) Descriptor() ([]byte, []int) {
	return file_pb_bls12_381_proto_rawDescGZIP(), []int{0}
}

func (x *Fr) GetE1() uint64 {
	if x != nil {
		return x.E1
	}
	return 0
}

func (x *Fr) GetE2() uint64 {
	if x != nil {
		return x.E2
	}
	return 0
}

func (x *Fr) GetE3() uint64 {
	if x != nil {
		return x.E3
	}
	return 0
}

func (x *Fr) GetE4() uint64 {
	if x != nil {
		return x.E4
	}
	return 0
}

// bls12-381 Fq q = 384 in big endian
type Fq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E1 uint64 `protobuf:"varint,1,opt,name=e1,proto3" json:"e1,omitempty"`
	E2 uint64 `protobuf:"varint,2,opt,name=e2,proto3" json:"e2,omitempty"`
	E3 uint64 `protobuf:"varint,3,opt,name=e3,proto3" json:"e3,omitempty"`
	E4 uint64 `protobuf:"varint,4,opt,name=e4,proto3" json:"e4,omitempty"`
	E5 uint64 `protobuf:"varint,5,opt,name=e5,proto3" json:"e5,omitempty"`
	E6 uint64 `protobuf:"varint,6,opt,name=e6,proto3" json:"e6,omitempty"`
}

func (x *Fq) Reset() {
	*x = Fq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_bls12_381_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fq) ProtoMessage() {}

func (x *Fq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bls12_381_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fq.ProtoReflect.Descriptor instead.
func (*Fq) Descriptor() ([]byte, []int) {
	return file_pb_bls12_381_proto_rawDescGZIP(), []int{1}
}

func (x *Fq) GetE1() uint64 {
	if x != nil {
		return x.E1
	}
	return 0
}

func (x *Fq) GetE2() uint64 {
	if x != nil {
		return x.E2
	}
	return 0
}

func (x *Fq) GetE3() uint64 {
	if x != nil {
		return x.E3
	}
	return 0
}

func (x *Fq) GetE4() uint64 {
	if x != nil {
		return x.E4
	}
	return 0
}

func (x *Fq) GetE5() uint64 {
	if x != nil {
		return x.E5
	}
	return 0
}

func (x *Fq) GetE6() uint64 {
	if x != nil {
		return x.E6
	}
	return 0
}

// bls12-381 Fq2 q = 384 in big endian
type Fq2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C1 *Fq `protobuf:"bytes,1,opt,name=c1,proto3" json:"c1,omitempty"`
	C2 *Fq `protobuf:"bytes,2,opt,name=c2,proto3" json:"c2,omitempty"`
}

func (x *Fq2) Reset() {
	*x = Fq2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_bls12_381_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fq2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fq2) ProtoMessage() {}

func (x *Fq2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bls12_381_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fq2.ProtoReflect.Descriptor instead.
func (*Fq2) Descriptor() ([]byte, []int) {
	return file_pb_bls12_381_proto_rawDescGZIP(), []int{2}
}

func (x *Fq2) GetC1() *Fq {
	if x != nil {
		return x.C1
	}
	return nil
}

func (x *Fq2) GetC2() *Fq {
	if x != nil {
		return x.C2
	}
	return nil
}

// bls12-381 g1 affine in big endian
type G1Affine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X        *Fq  `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y        *Fq  `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Infinity bool `protobuf:"varint,3,opt,name=infinity,proto3" json:"infinity,omitempty"`
}

func (x *G1Affine) Reset() {
	*x = G1Affine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_bls12_381_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G1Affine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G1Affine) ProtoMessage() {}

func (x *G1Affine) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bls12_381_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G1Affine.ProtoReflect.Descriptor instead.
func (*G1Affine) Descriptor() ([]byte, []int) {
	return file_pb_bls12_381_proto_rawDescGZIP(), []int{3}
}

func (x *G1Affine) GetX() *Fq {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *G1Affine) GetY() *Fq {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *G1Affine) GetInfinity() bool {
	if x != nil {
		return x.Infinity
	}
	return false
}

// bls12-381 g2 affine in big endian
type G2Affine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X        *Fq2 `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y        *Fq2 `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	Infinity bool `protobuf:"varint,3,opt,name=infinity,proto3" json:"infinity,omitempty"`
}

func (x *G2Affine) Reset() {
	*x = G2Affine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_bls12_381_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2Affine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2Affine) ProtoMessage() {}

func (x *G2Affine) ProtoReflect() protoreflect.Message {
	mi := &file_pb_bls12_381_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2Affine.ProtoReflect.Descriptor instead.
func (*G2Affine) Descriptor() ([]byte, []int) {
	return file_pb_bls12_381_proto_rawDescGZIP(), []int{4}
}

func (x *G2Affine) GetX() *Fq2 {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *G2Affine) GetY() *Fq2 {
	if x != nil {
		return x.Y
	}
	return nil
}

func (x *G2Affine) GetInfinity() bool {
	if x != nil {
		return x.Infinity
	}
	return false
}

var File_pb_bls12_381_proto protoreflect.FileDescriptor

var file_pb_bls12_381_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f, 0x33, 0x38, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f, 0x33, 0x38, 0x31, 0x22,
	0x44, 0x0a, 0x02, 0x46, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x65, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x65, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x65, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x65, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x65, 0x34, 0x22, 0x64, 0x0a, 0x02, 0x46, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x35, 0x12, 0x0e, 0x0a, 0x02, 0x65,
	0x36, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x65, 0x36, 0x22, 0x43, 0x0a, 0x03, 0x46,
	0x71, 0x32, 0x12, 0x1d, 0x0a, 0x02, 0x63, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f, 0x33, 0x38, 0x31, 0x2e, 0x46, 0x71, 0x52, 0x02, 0x63,
	0x31, 0x12, 0x1d, 0x0a, 0x02, 0x63, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f, 0x33, 0x38, 0x31, 0x2e, 0x46, 0x71, 0x52, 0x02, 0x63, 0x32,
	0x22, 0x60, 0x0a, 0x08, 0x47, 0x31, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f,
	0x33, 0x38, 0x31, 0x2e, 0x46, 0x71, 0x52, 0x01, 0x78, 0x12, 0x1b, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f, 0x33, 0x38, 0x31,
	0x2e, 0x46, 0x71, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x79, 0x22, 0x62, 0x0a, 0x08, 0x47, 0x32, 0x41, 0x66, 0x66, 0x69, 0x6e, 0x65, 0x12, 0x1c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c, 0x73, 0x31,
	0x32, 0x5f, 0x33, 0x38, 0x31, 0x2e, 0x46, 0x71, 0x32, 0x52, 0x01, 0x78, 0x12, 0x1c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6c, 0x73, 0x31, 0x32, 0x5f,
	0x33, 0x38, 0x31, 0x2e, 0x46, 0x71, 0x32, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_bls12_381_proto_rawDescOnce sync.Once
	file_pb_bls12_381_proto_rawDescData = file_pb_bls12_381_proto_rawDesc
)

func file_pb_bls12_381_proto_rawDescGZIP() []byte {
	file_pb_bls12_381_proto_rawDescOnce.Do(func() {
		file_pb_bls12_381_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_bls12_381_proto_rawDescData)
	})
	return file_pb_bls12_381_proto_rawDescData
}

var file_pb_bls12_381_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_bls12_381_proto_goTypes = []any{
	(*Fr)(nil),       // 0: bls12_381.Fr
	(*Fq)(nil),       // 1: bls12_381.Fq
	(*Fq2)(nil),      // 2: bls12_381.Fq2
	(*G1Affine)(nil), // 3: bls12_381.G1Affine
	(*G2Affine)(nil), // 4: bls12_381.G2Affine
}
var file_pb_bls12_381_proto_depIdxs = []int32{
	1, // 0: bls12_381.Fq2.c1:type_name -> bls12_381.Fq
	1, // 1: bls12_381.Fq2.c2:type_name -> bls12_381.Fq
	1, // 2: bls12_381.G1Affine.x:type_name -> bls12_381.Fq
	1, // 3: bls12_381.G1Affine.y:type_name -> bls12_381.Fq
	2, // 4: bls12_381.G2Affine.x:type_name -> bls12_381.Fq2
	2, // 5: bls12_381.G2Affine.y:type_name -> bls12_381.Fq2
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_bls12_381_proto_init() }
func file_pb_bls12_381_proto_init() {
	if File_pb_bls12_381_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_bls12_381_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Fr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_bls12_381_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Fq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_bls12_381_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Fq2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_bls12_381_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*G1Affine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_bls12_381_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*G2Affine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_bls12_381_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_bls12_381_proto_goTypes,
		DependencyIndexes: file_pb_bls12_381_proto_depIdxs,
		MessageInfos:      file_pb_bls12_381_proto_msgTypes,
	}.Build()
	File_pb_bls12_381_proto = out.File
	file_pb_bls12_381_proto_rawDesc = nil
	file_pb_bls12_381_proto_goTypes = nil
	file_pb_bls12_381_proto_depIdxs = nil
}
